### ISSUE TITLE
.prettierignoreいらない説？

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/official#135]
- https://github.com/uyupun/official/blob/main/.prettierignore ここでmdをprettierの対象外にしている
- しかし https://github.com/uyupun/official/blob/main/package.json#L19-L24 でjs,jsx,ts,tsxにlintの対象を絞っているのでいらないかも？

**Comment by tyokinuhata** [comment]
と思ったが、lint-staged経由ではない実行をした際に必要なのか

**Comment by tyokinuhata** [comment]
でもそれならlint-stagedとprettierで対象ファイルを揃えたほうが良い気がする

**Comment by tyokinuhata** [comment]
それとprettierでignoreの設定をするのであればeslintのignoreも設定したほうが良いのかもと思ったり

**Comment by takashi0602** [comment]
あー揃えた方がいいな...💦
jsonとかsvgとかも見てもらいたいし、設定見直します🙏
後、Prettierのv2.7からキャッシュが使えるようになった（ https://zenn.dev/sosukesuzuki/articles/1d1bfb73118a9b ）のでバージョン上げます＋ESLintも上げて、キャッシュオプションも付けるようにします🤮

**Comment by tyokinuhata** [comment]
- [ ] Prettierのバージョンアップ
- [ ] ESLintのバージョンアップ
- [ ] Prettierのキャッシュ設定
- [ ] ESLintのキャッシュ設定
- [ ] lint-stagedを別ファイルで管理
- [ ] lint-staged, prettierignore, eslintignoreの対象ファイルを揃える

**Comment by tyokinuhata** [comment]
Prettierのキャッシュはこの記事が詳しい: https://zenn.dev/sosukesuzuki/articles/1d1bfb73118a9b

**Comment by tyokinuhata** [comment]
キャッシュ戦略はパフォーマンスに影響が出ない限りデフォルトのままで良さそう(ただ明示的に指定しておいたほうが分かりやすそうなので `--cache-strategy content` は指定しておきたい)
