### ISSUE TITLE
新フォントの検討

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/official#145]
https://twitter.com/tawara_san/status/1623248439105695744?t=ysf7ATlywVAWT21xsihlGw&s=19

**Comment by takashi0602** [comment]
これ良さげかも
https://github.com/yuru7/udev-gothic

参考: https://twitter.com/Comamoca_/status/1625118242326061058

**Comment by takashi0602** [comment]
next/fontも使いたい

**Comment by tyokinuhata** [comment]
https://twitter.com/maslow_design/status/1637368084465074176?t=gtJiPHZWn9_MZnpOoQpYBg&s=19

**Comment by tyokinuhata** [comment]
https://tanukifont.com/sil/

**Comment by takashi0602** [comment]
Webフォントの提供元の記述方法
https://yomotsu.net/blog/2012/10/09/webfont-license.html

**Comment by tyokinuhata** [comment]
Cicaでひとまず決定かな？

**Comment by tyokinuhata** [comment]
https://twitter.com/matsuu/status/1659914225106534400?t=APEfaH25w4MCrdt1ELnfGw&s=19

**Comment by tyokinuhata** [comment]
https://twitter.com/madonomori/status/1663793507881082887?t=K2eZxqAW39wetqVnjTVtuw&s=19

**Comment by tyokinuhata** [comment]
https://twitter.com/n_yuji/status/1674685106794151936?t=e2eXPN4ds4Mib_7jz4U-wg&s=19

**Comment by takashi0602** [comment]
Cicaが採用されました
https://github.com/miiton/Cica

**Comment by tyokinuhata** [comment]
Cicaちゃんが採用されました
