### ISSUE TITLE
@vanilla-extract/babel-plugin が非推奨になってたので削除する

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#149]
## 概要

[@vanilla-extract/babel-plugin](https://www.npmjs.com/package/@vanilla-extract/babel-plugin) が非推奨になっていたので削除する。Storybook周りでエラーになると思われるので、以下参考に対応する。
参考: https://qiita.com/tsuka8888/items/b2cc1e53af245e387933

**Comment by takashi0602** [comment]
[メモ]
現状では上記参考にしても起動しない。
（Next.jsとReactのバージョン上げたらいけるかも🤔）

**Comment by takashi0602** [comment]
storybook-addon-nextも非推奨になっていたので、[@storybook/nextjs](https://www.npmjs.com/package/@storybook/nextjs)を使用する

**Comment by tyokinuhata** [comment]
こちら別issueに分割しました

https://github.com/uyupun/official/issues/225
