### ISSUE TITLE
リンターの導入

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#15]

**Comment by takashi0602** [comment]
airbnbのやつ入れたい

**Comment by tyokinuhata** [comment]
そういえばPrettierってどうするんだっけ

**Comment by takashi0602** [comment]
一旦保留

**Comment by tyokinuhata** [comment]
もうちょっとベストプラクティスを探ってから対応

**Comment by takashi0602** [comment]
airbnb入れる or 他のやつ入れる or 独自ルール or 今のままのどれか対応する

**Comment by takashi0602** [comment]
ESLintのinit時に選択できる [eslint-config-standard-with-typescript](https://github.com/standard/eslint-config-standard-with-typescript) これを入れるのが良さそう

**Comment by tyokinuhata** [comment]
これ、現状のESLintの設定でなにか不満があったんだっけ？

**Comment by tyokinuhata** [comment]
Osakanaのほうと設定が揃うみたいなメリットはありそうすけど

**Comment by takashi0602** [comment]
まあ最低限のプラグインしか設定してないから、もう少し厳しくしたい気持ちはあるな（↓現状）
`"extends": ["next/core-web-vitals", "next", "prettier"],`

**Comment by tyokinuhata** [comment]
なるほど、ほな入れますか
