### ISSUE TITLE
コンポーネントで React.ComponentProps を使用する

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#153]
## 参照

https://zenn.dev/takepepe/articles/atoms-type-definitions

**Comment by tyokinuhata** [comment]
https://twitter.com/tonkotsuboy_com/status/1683747639144386562?s=46&t=k8x-_fZZ9oLgDQFZ34YSlQ

**Comment by takashi0602** [comment]
- refの使用を明記した方が良さそうなので、`ComponentPropsWithoutRef`と`ComponentPropsWithRef`を使うのが良さそう
- 型を使用する側では`ComponentProps<Component Name>`とする
