### ISSUE TITLE
各ページで使用するコンポーネントの洗い出し

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#200]
## 概要

BCCDに沿ってFigma上からコンポーネントを洗い出す（基本的にCaseとDomain）

**Comment by takashi0602** [comment]
ミッション / ビジョン / バリュー / ポートフォリオ（詳細） / コンタクトフォーム

**Comment by tyokinuhata** [comment]
こないだ話してた、TechnologyBadge / Accordion / ImageLinkが今の分類で本当に良いのかも確認しておいてほしい〜

**Comment by takashi0602** [comment]
📝
TechnologyBadgeはCommonに分類できそう

**Comment by takashi0602** [comment]
洗い出し＋issue化したため、このissueはCloseします
