### ISSUE TITLE
scriptsはsrc内に作成した方が良さそうかも

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/official#206]

**Comment by tyokinuhata** [comment]
src内にもpublicを参照しているコードはあるし、逆にsrc外には基本的に設定ファイル以外のコードは置いてない気がする

**Comment by tyokinuhata** [comment]
src/libが肥大化していきそうではあるんですよねえ、、、
pathpidaはsrc/libに置くことが多いんですか？

**Comment by takashi0602** [comment]
pathipdaはデフォルトが、src/libかsrc/utilsのどっちかなんよね
src/libがそこまで肥大化するようなことはないとは思うものの分けててもよさそうではあるよな
src/libはpathipidaとかの自動生成のコードの置き場所てきな感じの位置付けにして

**Comment by tyokinuhata** [comment]
デフォルトが２つあるってどゆこと？？
というかそもそもsrc/utilsとsrc/libsってどういう分け方なのかいまいちピンとこないな
どちらか一つでも良いような気がする

**Comment by takashi0602** [comment]
公式は↓こんな感じやね
https://github.com/aspida/pathpida#usage---nextjs

> src/lib/$path.ts or src/utils/$path.ts // Generated automatically by pathpida

**Comment by tyokinuhata** [comment]
一方でscriptsは別にユーティリティではないので別途src/scripts作ったほうが良さそうと思った

**Comment by tyokinuhata** [comment]
pathpidaはutilsに変えますか

**Comment by takashi0602** [comment]
よさそう
↓みたいなかんじってことっすね！

```
lib/$path.ts => src/utils/$path.ts
scripts => src/scripts
```
