### ISSUE TITLE
GitHub PagesにデプロイされたStorybookで画像が見れない

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#216]
## 概要

GitHub PagesにデプロイされたStorybookでpublic/以下にある画像が見れないのでデプロイ時にpublic/以下の画像を読み込めるように修正お願いします

**Comment by takashi0602** [comment]
画像だけではなく、フォントも適応されてなかったっす🙏

**Comment by tyokinuhata** [comment]
んー、多分全体的にパスがおかしい

**Comment by tyokinuhata** [comment]
本来はここを指さないといけない
https://uyupun.github.io/official/main/storybook/images/zeus/zeus.avif

**Comment by tyokinuhata** [comment]
ビルド時のオプションを変えたらいけるのか、Storybookのコードをいじらないといけないのか、、、

**Comment by tyokinuhata** [comment]
コードいじる可能性も考えて一応 @takashi0602 もアサインに追加した

**Comment by tyokinuhata** [comment]
ローカルで起動する場合は`/images/xx`でアクセスできるけど、GitHub Pagesからは`/official/branch_name/storybook/images/xx`でアクセスしないといけない

**Comment by tyokinuhata** [comment]
Pathpidaの設定を変えて相対パスにしないといけない？？

**Comment by takashi0602** [comment]
Storybook内ではpathpida使わないようにするのがよさそう🤔

**Comment by tyokinuhata** [comment]
とはいえ、Pathpidaの定義を相対パスにするのって良くなさそうよな、、、
Storybookだけ例外でPathpida使わずに相対パスで指定するようにする？

**Comment by takashi0602** [comment]
それがよさそう
後は、フォントが読まれてないも対応しないといけないけど、これは別途.storybook/以下にcssファイル作成するのが早そうやわ

**Comment by tyokinuhata** [comment]
試しにローカルでビルドしてみたけど、やっぱりこっちでも見れてない

![](https://github.com/uyupun/official/assets/16177316/76c34e3b-9bf6-4924-a1a4-c195dfdc785b)

**Comment by takashi0602** [comment]
いや、そうでもないんかな🤔
ちょっと試してみますわ

**Comment by tyokinuhata** [comment]
おねしゃす

**Comment by tyokinuhata** [comment]
たかしのアサインで大丈夫そう？

**Comment by takashi0602** [comment]
大丈夫です🙆‍♂️
治せたんでPR投げます
