### ISSUE TITLE
next/fontを使用してフォントを読み込む

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#221]
## 概要

next/fontを使用してフォントを読み込むようにする。現状nextjsビルド後にフォントが正しく読み込まれていないため。
`_app.ts` につかすればよさそう
https://nextjs.org/docs/app/building-your-application/optimizing/fonts#local-fonts
https://zenn.dev/siino/articles/b42d658af571f0

**Comment by tyokinuhata** [comment]
これって開発サーバでは読み込まれてるけど本番ビルドでは読み込まれてないっていう話？

**Comment by takashi0602** [comment]
ですね

**Comment by tyokinuhata** [comment]
`next/font`ってGoogle Fontsに無いフォントでもいけるの？

**Comment by takashi0602** [comment]
こんな感じでローカルのフォント読み込めるらしいっす
```ts
import localFont from 'next/font/local'
 
// Font files can be colocated inside of `app`
const myFont = localFont({
  src: './my-font.woff2',
  display: 'swap',
})
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={myFont.className}>
      <body>{children}</body>
    </html>
  )
}
```

**Comment by takashi0602** [comment]
これ、普通に見れてました🙇‍♂️
ただ、next/font使った方が若干やけどパフォーマンスよさそうなんで対応します🫡

**Comment by takashi0602** [comment]
next/font、[Next.js Compiler](https://nextjs.org/docs/architecture/nextjs-compiler)（SWC）のみに対応していて、現状`@vanilla-extract`でbabelの設定を記述しているので↑がオプトアウトしてるので動かない...
なので先に https://github.com/uyupun/official/issues/149 このissueから対応しないとダメですね😢

**Comment by tyokinuhata** [comment]
そして #149 の対応をするにはStorybookのバージョンを上げる必要があるｗ

**Comment by tyokinuhata** [comment]
@takashi0602 今ってNext.js自体はSWCを使用しているものの、vanilla-extractが部分的にBabelに依存しているみたいな感じなんですか？

**Comment by tyokinuhata** [comment]
そもそもbabel-pluginはなんのために使ってるんですか？

**Comment by takashi0602** [comment]
昔は@vanilla-extractをNextjsで動かすために必要だった(公式のドキュメントに書いてた)んですけど、なんか気がついたら非推奨になってたんですよね
今は非推奨になったので不要なはず

**Comment by tyokinuhata** [comment]
なるほどな、完全に理解した

**Comment by takashi0602** [comment]
合わせてこちらも対応する: https://github.com/uyupun/official/issues/250
