### ISSUE TITLE
Storybookでのみ使用している画像を`/public/images/*`に含めるのに違和感がある

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/official#222]
- Storybookのベストプラクティスをあんまり理解していないのでアレなんですが、肌感として、プロダクト自体からは参照されない画像が`/public/images/*`以下に存在することに違和感を感じた
- 具体的にどうすれば良いのかとかそういう部分まで考えられているわけではないですが、とりあえず報告

**Comment by tyokinuhata** [comment]
ビルドのサイズも大きくなるような気がしている

**Comment by takashi0602** [comment]
まあ別途Storybook用に画像用意するのはありではあるけど、どうするのかは分からないので調べます🫡

**Comment by tyokinuhata** [comment]
たしかにプロダクトから参照される画像をサンプル画像として使うなら良いのか

**Comment by tyokinuhata** [comment]
このゼウスくんラフ画像だったからStorybook用のサンプル画像という立ち位置なのかと思ってたｗ

**Comment by takashi0602** [comment]
なるほどw

**Comment by tyokinuhata** [comment]
閉じて良さそうっすね
