### ISSUE TITLE
ts-nodeの導入を検討する

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/official#244]

**Comment by tyokinuhata** [comment]
- ES Modules形式にしたい
- TypeScriptにしたい

**Comment by tyokinuhata** [comment]
- つまり、`tsconfig.json`と`package.json`の設定で、モジュールの方式が一致している必要がある
- TypeScriptのモジュールをCommonJSにする場合、`src/scripts`専用の`tsconfig.json`を作成し、別途設定したほうが良さそう
- JavaScriptのモジュールをES Modulesにする場合、`package.json`への設定が必要で、その影響がリポジトリ全体に及ぶため、`src/scripts`以下に無いJSについても考慮する必要がある(例えば`next.config.js`とか`.lintstagerc.js`)

**Comment by takashi0602** [comment]
> tsconfig.jsonでmoduleをesnextにしているため、TypeScriptからはES Modulesが使えるようになっているが、package.jsonのtypeでmoduleを指定していないため、CommonJSでないと実行に失敗する

これに関しては誤りで、tsconfig.jsonのmoduleはどの形式で出力するかなので、ES Modulesが使えるようなるわけではなさそう

- refs.
  - https://gist.github.com/azu/56a0411d69e2fc333d545bfe57933d07
  - https://www.typescriptlang.org/tsconfig#module

package.jsonで`"type": "module"`にすることで、`.js`ファイルがES Modulesとして扱うようになり、既存のCommonJSのファイルは`.cjs`の拡張子にすることでそのままの記述で使用できる。
Next.js（`next.config.js`）は`"type": "module"`にも対応してそう（公式ドキュメントが変わりすぎてて、公式ドキュメントからは見つけられなかった）
ref. https://zenn.dev/link/comments/460ec1c4e4d839

`.lintstagerc.js`とかは`.lintstagerc.cjs`にしてCommonJSとして扱うのが良さそう（ESLintもinitした際にeslintrc.cjsが生成されたので他の設定周りも拡張子変更で良さそう）

**Comment by takashi0602** [comment]
ただ、影響範囲が大きいそうなので、scripts以下のファイルの拡張子を`.mjs`にしES Modulesとして扱うようにするのが良さそうな気がする。

**Comment by tyokinuhata** [comment]
scripts以下のファイルを`.mjs`にしたらそれはJSであってTSでないと思うんですよね
そして.mtsみたいな拡張子はなさそう

**Comment by tyokinuhata** [comment]
> tsconfig.jsonのmoduleはどの形式で出力するかなので、ES Modulesが使えるようなるわけではなさそう

これはその通りで、現状はTS側ではES Modulesで出力するようになっているが、JS側がCommonJSとして扱うようになっているのが問題

**Comment by tyokinuhata** [comment]
なんで、基本的には`package.json`の`type`に`module`を指定し、対応していないものは部分的に`.cjs`に変更するというのが良い着地点である気がしてきたな
そしてscripts以下はES Modules形式のTSで記述する

**Comment by takashi0602** [comment]
勘違い失礼しました🙏🙏🙏

> なんで、基本的にはpackage.jsonのtypeにmoduleを指定し、対応していないものは部分的に.cjsに変更するというのが良い着地点である気がしてきたな
> そしてscripts以下はES Modules形式のTSで記述する

とりあえずこれでいきましょ！
ちな`next.config.js`はTSでは書けませんでした😢
https://nextjs.org/docs/pages/building-your-application/configuring/typescript#type-checking-nextconfigjs

**Comment by tyokinuhata** [comment]
TS + ES Modules -> JS + ES Modules -> JS + CommonJS の優先順位でやる

**Comment by tyokinuhata** [comment]
念のため、Next.jsで使用しているTSのバージョンと揃得ている方が良さそう

**Comment by takashi0602** [comment]
v4.5.2以上を推奨していて、今の使用してるのがv4.9.5なので大丈夫そう
https://nextjs.org/docs/pages/building-your-application/configuring/typescript#minimum-typescript-version

> It is highly recommended to be on at least v4.5.2 of TypeScript to get syntax features such as [type modifiers on import names](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names) and [performance improvements](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#real-path-sync-native).

**Comment by tyokinuhata** [comment]
あー、そうか。ts-nodeもtscに依存しているから良いのか。

**Comment by tyokinuhata** [comment]
メモ
- 実装に先立って、影響範囲と検証項目を洗い出しておく

**Comment by tyokinuhata** [comment]
- [ ] `.lintstagedrc.js`
- [ ] `.svgrrc.js`
- [ ] `changelog.config.js`
- [ ] `next.config.js`
- [ ] `src/scripts/generateImages.js`
- [ ] `src/scripts/lighthouse.js`
