### ISSUE TITLE
各画面のモーダルのデザインをやめる

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#252]
## 概要

以下を考慮して、モーダルのデザインをやめる方向になった

- 画面遷移周りを考慮しないといけない
- モーダル+アニメーションも実装が難しい
- トップ以外はWebGLが描画されなくなるので、動作が軽くなる

## 懸念

- WebGLの描画までのローディングUI的なものを考えないといけない

**Comment by tyokinuhata** [comment]
デザインモックの修正も発生しそう

**Comment by takashi0602** [comment]
Figmaに反映しました！
