### ISSUE TITLE
chromaticで毎回差分が出る原因の特定と対応

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#267]
## 概要

UIを変更していないのにも関わらず、毎回差分が出る。そのため原因の特定と対応を行う。
（画像に背景色つけるのがよくない？？）

**Comment by takashi0602** [comment]
サポートに問い合わせたので続報待ち。。。

**Comment by takashi0602** [comment]
返信が来たので記載

> Hey Takashi - Suki with Chromatic here!
> It looks like you haven't ran a build for the main branch. Would you mind running a build for this branch and let me know if you're receiving an error?
> 訳
> やあ、タカシ - ChromaticのSukiです！
> メインブランチのビルドがまだのようですね。このブランチのビルドを実行して、エラーが発生したら教えてもらえますか？

**Comment by takashi0602** [comment]
ローカルで `$ npx chromatic --project-token <your-project-token>` を打ったら最新のになった。なんで更新されなかったのかは現在質問中。。。
ref: https://www.chromatic.com/docs/setup/#run-chromatic

**Comment by takashi0602** [comment]
> Hey Takashi - thanks for your patience!
Awesome to hear that the branch is finally reflecting as updated, that's great news! 🎉 Regarding your question of why this is happening, this could be a number of reasons. Would you mind sharing your GitHub Actions .yml config so I can see how you have your workflow set up?

yamlファイル見せてと言われたので、以下リンク送った
https://github.com/uyupun/official/blob/main/.github/workflows/deploy-chromatic.yml

**Comment by takashi0602** [comment]
@tyokinuhata 

`branches-ignore`に`main`があるのが原因っぽいねんけど、ここの`main`削除してもCIに影響ないか調査してほしい🙏
https://github.com/uyupun/official/blob/54ced8f4e2f63b760d80523244ee2ee654646624/.github/workflows/deploy-chromatic.yml#L6

**Comment by tyokinuhata** [comment]
動作自体には影響ないっすね、 `main` ブランチでChromatic見ないからいらんやろーということでignoreしていた
まさかこれが悪さしてるとはｗ

**Comment by tyokinuhata** [comment]
てかめちゃくちゃサポート丁寧やな、、、

**Comment by takashi0602** [comment]
調査アザス！
サポートはまじで丁寧でやり取りしてても苦にならなかったっす😌

**Comment by tyokinuhata** [comment]
対応済みのためclose

**Comment by takashi0602** [comment]
Chromatic上でも確認済み🫶
