### ISSUE TITLE
.svgrrc.cjs内のテンプレートを別ファイルで記述

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#282]
## 概要

シンタックスハイライトが効かないので、別ファイルで定義したものをテンプレートに記述することができるか調査する

https://github.com/uyupun/official/pull/281#discussion_r1272114446

**Comment by tyokinuhata** [comment]
ちなみにテンプレに対してもESLintはかかっている？

**Comment by takashi0602** [comment]
> ちなみにテンプレに対してもESLintはかかっている？

これはかかってます

**Comment by takashi0602** [comment]
調べた感じ、テンプレートを別ファイルで定義するのは可能だけど、シンタックスハイライトが付くようにするのは無理ですね。。。💦

**Comment by tyokinuhata** [comment]
これは対応を諦める方向で考えても良いかもしれない
