### ISSUE TITLE
背景グラデーションにする

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#296]
青系がよさそう

**Comment by tyokinuhata** [comment]
海に沈んでいくイメージ。深海少女

**Comment by tyokinuhata** [comment]
結局グラーデションにはしないことにしたためclose

**Comment by tyokinuhata** [comment]
これでもう一度試してみる？
https://cssgradient.io/gradient-backgrounds/

**Comment by tyokinuhata** [comment]
良さそうな例: https://www.insuredao.fi/

**Comment by tyokinuhata** [comment]
これも良さそう？: https://nori.com/

**Comment by takashi0602** [comment]
対応しました！
