### ISSUE TITLE
コピーライトを追記する

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/official#304]
はい、著作権は作品が創作された時点で自動的に発生します。コピーライトの表記（例：© 2023 All Rights Reserved）がなくてもその作品は著作権で保護されています。

コピーライトの表記を行う理由は以下のようなものがあります：

1. *明確性*: 表記によって、その作品やコンテンツが著作権で保護されていることを明確に伝えることができます。これにより、第三者が無許可での利用や複製をためらう可能性が高まります。

2. *所有権の提示*: コピーライトの表記をすることで、誰がその作品の著作権者（または権利者）であるのかを明示できます。

3. *国際的な保護*: 一部の国々では、著作権の表記がないと著作権の権利を完全に行使できない場合があります。コピーライトの表記をしておくことで、国際的な文脈でも権利を保護しやすくなります。

4. *著作権侵害の争い*: 万が一、著作権侵害の争いが生じた場合、コピーライトの表記があると、作品の権利者が自身の権利を主張しやすくなります。

5. *一般的な慣習*: 多くのウェブサイトや出版物でコピーライトの表記が行われているため、これを模倣することで公式感や信頼性を高める効果があると考えられます。

要するに、コピーライトの表記は法的な義務ではないものの、著作権の権利を強化し、第三者へのメッセージとしても効果的です。

**Comment by tyokinuhata** [comment]
参考: https://tributelabs.xyz/

**Comment by takashi0602** [comment]
Figmaに追加したのでCloseします
