### ISSUE TITLE
既存のコンポーネントのデザインを修正

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#305]
## 概要

デザインが刷新されたので、それに合わせて既存のコンポーネントのデザインを修正する

**Comment by takashi0602** [comment]
📝 Textコンポーネントは `@vanilla-extract/dynamic` を使用すればフォントサイズを動的に変更できそう
無理なら `style` 属性に直書きでもよさげ

**Comment by tyokinuhata** [comment]
可能であればコンポーネント毎にPRほしいです

**Comment by takashi0602** [comment]
対応済みのためCloseします
