### ISSUE TITLE
Chromaticの導入検討

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#31]
https://www.chromatic.com/

Storybookのホスティングサービス
視覚的なリグレッションテストが可能

**Comment by tyokinuhata** [comment]
CI/CDにテストはさせたいのでそこらへんも考える

**Comment by tyokinuhata** [comment]
これも検討してみてもいいかも
https://github.com/reg-viz

**Comment by takashi0602** [comment]
https://www.chromatic.com/docs/ci.html#configure-ci
