### ISSUE TITLE
フォント決める

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#48]
文章とタイトルでフォント分けたほうが良さそう

**Comment by takashi0602** [comment]
文章
[Noto Sans Japanese](https://fonts.google.com/noto/specimen/Noto+Sans+JP)
[Noto Serif Japanese](https://fonts.google.com/noto/specimen/Noto+Serif+JP)

**Comment by takashi0602** [comment]
タイトル
ゴシック体とかスクリプト体とかかな

**Comment by tyokinuhata** [comment]
英語はサンセリフ体、日本語はゴシック体にしたいね

**Comment by tyokinuhata** [comment]
チームの大半がエンジニアということもあるので、そういうバックグラウンドからRictyを採用するのも悪くないかもしれない
https://rictyfonts.github.io/

**Comment by tyokinuhata** [comment]
もしくはデザインモックと同様、Robotoを採用するか
https://fonts.google.com/specimen/Roboto

**Comment by takashi0602** [comment]
一旦 `RictyDiminished` で対応する
https://github.com/edihbrandon/RictyDiminished
