### ISSUE TITLE
Settings > Secret > Dependabot 以下に chromatic のトークンを追加する

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#59]
- [x] Dependabot secrets はそもそもセキュリティ的に問題ないか調査する
- [x] PR #55 を Revert する
- [x] chromatic のトークンを追加する
- [x] CIで転けず、かつ chromatic がスキップされるかどうかを検証する

**Comment by tyokinuhata** [comment]
これDependabotが作ったPRが無いと厳密な検証ができないのでどうしようってかんじ

**Comment by tyokinuhata** [comment]
関連issue: #52

**Comment by takashi0602** [comment]
なんかできてた
