### ISSUE TITLE
CSS設計調査

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/official#7]

**Comment by takashi0602** [comment]
- ScopedでないCSSの場合、BEM、FLOCSSが好まれる
- FLOCSSの場合、設計自体が大きいので好き嫌いが分かれやすい
- 近年はScopedなCSSが主流ということもあり、CSS設計を考えることが少なくなった
  - 他にも、CSS in JSやTailwindCSSの普及により、CSS設計を考えずともコーディングできるようになった
- ScopedなCSSの場合、コンポーネントなどの小さな単位になるためBEMが好まれる

今回は [Emotion](https://emotion.sh/) を使用し、Emotionの中でもStyledを使用した記述で作成する
https://emotion.sh/docs/styled

**Comment by tyokinuhata** [comment]
scopedなCSSを使う場合でも、そのスコープ内で設計するという認識で合ってる...?
そうではなく、全体で共通のCSSを定義しておく部分のみ設計する？

**Comment by takashi0602** [comment]
> scopedなCSSを使う場合でも、そのスコープ内で設計するという認識で合ってる...?

上記認識であってます🙆‍♂️
今回はBEMが良さそうなので、BEMを元に設計していくつもりです

**Comment by tyokinuhata** [comment]
なるほど、完全理解

**Comment by takashi0602** [comment]
@tyokinuhata 
vanilla-extract の書き方は、↓みたいになるのでそこまでBEMを意識しなくても良さそうだけど、一応BEMを意識しつつ命名しようかなと思ってる

```
import { style } from '@vanilla-extract/css';

const example = style({
  color: 'red',
});

const Example = () => {
  return <div className="{example}">赤色</div>
}
```

**Comment by takashi0602** [comment]
READMEに以下を記載する
CSS設計についてはBEMを用いる
https://en.bem.info/
