### ISSUE TITLE
Next 13にバージョンアップ

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/official#70]

**Comment by takashi0602** [comment]
- [ ] next を v13.1.6 にする
  - [ ] eslint-config-next を v13.1.6 にする
  - [ ] @next/font の v13.1.6 を導入 
- [ ] react / react-dom を v18.2.0 にする
  - [ ] @types/react / @types/react-dom を v18.0.28 / v18.0.11 にする
- [ ] @types/node を v18.14.0 にする
- [ ] typescript を v4.9.5 にする

**Comment by tyokinuhata** [comment]
`@types/hogehoge` 系のライブラリのバージョンは何を基準に決めたんだっけ:thinking-face:

**Comment by takashi0602** [comment]
> @next/font に関しては別PRで対応しましょか(新しいライブラリを入れる変更を混ぜると分かりにくそうなので)

このPRでは入れない予定です！(もしnextのv13に依存してたら入れる感じで記述してます🙏)

> @types/hogehoge 系のライブラリのバージョンは何を基準に決めたんだっけ:thinking-face:

全部latestだったはずやけど、create next appした時に入ったバージョンっす👍

**Comment by takashi0602** [comment]
2023/03/12現在のlatestのpackage.json内部

```
{
  "name": "sample",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "18.15.0",
    "@types/react": "18.0.28",
    "@types/react-dom": "18.0.11",
    "eslint": "8.36.0",
    "eslint-config-next": "13.2.4",
    "next": "13.2.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.5"
  }
}
```
