### ISSUE TITLE
モーダル（ダイアログ）の削除

### ISSUE THREAD

**Issue by takashi0602** [uyupun/official#76]
## 概要

headless ui使用する
https://headlessui.com/react/dialog

URLを変えれるような感じで実装する
https://kouki.hatenadiary.com/entry/2021/06/03/100000

**Comment by takashi0602** [comment]
- [ ] 閉じるアイコンボタンの追加

**Comment by tyokinuhata** [comment]
グリッジ

**Comment by takashi0602** [comment]
Three.jsのGlitchPass良さげ
https://tsudoi.org/glsl/effectcomposer/00/

**Comment by takashi0602** [comment]
📝  ページ遷移周りを考慮しないといけないため、モーダル（ダイアログ）は使用しない方向になりそう

**Comment by takashi0602** [comment]
モーダルは使用しなくなる想定のため削除する

**Comment by tyokinuhata** [comment]
モーダル「風」のコンポーネントを作ることになるのかな？

**Comment by takashi0602** [comment]
デザイン練り直してからかな🤔
画面遷移時に↓のGlitchPass選択した時みたいなやつ入れたいからその辺りも合わせて考えたいね💦
https://tsudoi.org/demo/glsl/effectcomposer/00/

**Comment by tyokinuhata** [comment]
なるほど、了解した
